<?php

declare(strict_types=1);

namespace Nowo\AuthKitBundle\DependencyInjection;

use Nowo\AuthKitBundle\Enum\AuthEmbedMode;
use Nowo\AuthKitBundle\Enum\PasswordResetDeliveryMode;
use Nowo\AuthKitBundle\Enum\PasswordResetMode;
use Nowo\AuthKitBundle\Enum\RegistrationMode;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration tree for AuthKitBundle.
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_auth_kit';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $root        = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('user_class')
                    ->info('FQCN of the application user entity (must implement UserInterface).')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->example('App\\Entity\\User')
                ->end()
                ->scalarNode('user_identifier_field')
                    ->info('Entity property used as the security user identifier (form_login username).')
                    ->defaultValue('email')
                    ->cannotBeEmpty()
                ->end()
                ->scalarNode('registration_role')
                    ->info('Role assigned to users created via registration (in addition to ROLE_USER from the entity).')
                    ->defaultValue('ROLE_USER')
                    ->cannotBeEmpty()
                ->end()
                ->enumNode('registration_mode')
                    ->values(array_map(static fn (RegistrationMode $mode): string => $mode->value, RegistrationMode::cases()))
                    ->info('disabled: no registration. first_user_only: register only when no users exist. always: open registration.')
                    ->defaultValue(RegistrationMode::FirstUserOnly->value)
                ->end()
                ->arrayNode('login_fields')
                    ->info('Login form fields. Use identifier (maps to user_identifier_field), password, remember_me.')
                    ->defaultValue(['identifier', 'password'])
                    ->prototype('variable')->end()
                ->end()
                ->arrayNode('registration_fields')
                    ->info('Registration form fields. String names or arrays with name, type, property, hash, required.')
                    ->defaultValue(['email', 'password'])
                    ->prototype('variable')->end()
                ->end()
                ->arrayNode('templates')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('layout')
                            ->defaultValue('@NowoAuthKitBundle/layout.html.twig')
                        ->end()
                        ->scalarNode('login')
                            ->defaultValue('@NowoAuthKitBundle/security/login.html.twig')
                        ->end()
                        ->scalarNode('register')
                            ->defaultValue('@NowoAuthKitBundle/security/register.html.twig')
                        ->end()
                        ->scalarNode('reset_request')
                            ->defaultValue('@NowoAuthKitBundle/security/reset_request.html.twig')
                        ->end()
                        ->scalarNode('reset_password')
                            ->defaultValue('@NowoAuthKitBundle/security/reset_password.html.twig')
                        ->end()
                        ->scalarNode('reset_password_code')
                            ->defaultValue('@NowoAuthKitBundle/security/reset_password_code.html.twig')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('embed')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('mode')
                            ->values(array_map(static fn (AuthEmbedMode $mode): string => $mode->value, AuthEmbedMode::cases()))
                            ->info('disabled: full-page routes only. dropdown: embed login/register via auth_kit_dropdown().')
                            ->defaultValue(AuthEmbedMode::Disabled->value)
                        ->end()
                        ->booleanNode('show_login')
                            ->info('Include the login form in the embedded UI.')
                            ->defaultTrue()
                        ->end()
                        ->booleanNode('show_register')
                            ->info('Include registration when allowed by registration_mode.')
                            ->defaultTrue()
                        ->end()
                        ->scalarNode('template')
                            ->defaultValue('@NowoAuthKitBundle/embed/dropdown.html.twig')
                        ->end()
                        ->scalarNode('login_panel')
                            ->defaultValue('@NowoAuthKitBundle/embed/_login_panel.html.twig')
                        ->end()
                        ->scalarNode('register_panel')
                            ->defaultValue('@NowoAuthKitBundle/embed/_register_panel.html.twig')
                        ->end()
                        ->scalarNode('authenticated')
                            ->defaultValue('@NowoAuthKitBundle/embed/_authenticated.html.twig')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('password_reset')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('mode')
                            ->values(array_map(static fn (PasswordResetMode $mode): string => $mode->value, PasswordResetMode::cases()))
                            ->info('disabled: hide reset flows. enabled: expose request and completion routes.')
                            ->defaultValue(PasswordResetMode::Disabled->value)
                        ->end()
                        ->enumNode('delivery')
                            ->values(array_map(static fn (PasswordResetDeliveryMode $mode): string => $mode->value, PasswordResetDeliveryMode::cases()))
                            ->info('link: URL token. code: OTP/SMS/email code. both: link URL and code for notifiers.')
                            ->defaultValue(PasswordResetDeliveryMode::Link->value)
                        ->end()
                        ->integerNode('token_ttl')
                            ->info('Seconds until the reset credential expires.')
                            ->defaultValue(3600)
                            ->min(60)
                        ->end()
                        ->integerNode('token_bytes')
                            ->info('Entropy for link tokens (bytes before hex encoding).')
                            ->defaultValue(32)
                            ->min(16)
                        ->end()
                        ->integerNode('code_length')
                            ->defaultValue(6)
                            ->min(4)
                            ->max(12)
                        ->end()
                        ->enumNode('code_charset')
                            ->values(['numeric', 'alphanumeric'])
                            ->defaultValue('numeric')
                        ->end()
                        ->scalarNode('token_field')
                            ->info('User entity property storing the hashed reset credential.')
                            ->defaultValue('passwordResetToken')
                        ->end()
                        ->scalarNode('token_expires_field')
                            ->info('User entity property storing credential expiry.')
                            ->defaultValue('passwordResetExpiresAt')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('routes')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('login')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('path')->defaultValue('/login')->end()
                                ->scalarNode('name')->defaultValue('nowo_auth_kit_login')->end()
                            ->end()
                        ->end()
                        ->arrayNode('logout')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('path')->defaultValue('/logout')->end()
                                ->scalarNode('name')->defaultValue('nowo_auth_kit_logout')->end()
                            ->end()
                        ->end()
                        ->arrayNode('register')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('path')->defaultValue('/register')->end()
                                ->scalarNode('name')->defaultValue('nowo_auth_kit_register')->end()
                            ->end()
                        ->end()
                        ->arrayNode('reset_request')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('path')->defaultValue('/reset-password')->end()
                                ->scalarNode('name')->defaultValue('nowo_auth_kit_reset_password_request')->end()
                            ->end()
                        ->end()
                        ->arrayNode('reset_password')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('path')->defaultValue('/reset-password/reset/{token}')->end()
                                ->scalarNode('name')->defaultValue('nowo_auth_kit_reset_password')->end()
                            ->end()
                        ->end()
                        ->arrayNode('reset_password_code')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('path')->defaultValue('/reset-password/complete')->end()
                                ->scalarNode('name')->defaultValue('nowo_auth_kit_reset_password_code')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('firewall')
                    ->info('Symfony firewall name where form_login should point (documented for security.yaml).')
                    ->defaultValue('main')
                ->end()
                ->scalarNode('login_success_route')
                    ->info('Route name after successful login. Null uses firewall default_target_path.')
                    ->defaultNull()
                ->end()
                ->scalarNode('default_locale')
                    ->defaultValue('en')
                ->end()
                ->arrayNode('enabled_locales')
                    ->scalarPrototype()->end()
                    ->defaultValue(['en', 'es'])
                ->end()
                ->booleanNode('locale_in_path')
                    ->info('Prefix login, register, logout and password reset routes with /{_locale}.')
                    ->defaultFalse()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
